routes/web.php
<?php

use App\Http\Controllers\ActivityController;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\ContactNoteController;
use App\Http\Controllers\ContactsAdminController;
use App\Http\Controllers\ContactsController;
use App\Http\Controllers\TagsController;
use App\Http\Controllers\TaskController;
use App\Http\Controllers\TrushCompanyController;
use App\Http\Controllers\TrushContactsController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

//Route::get('/contacts', function () {
//    $contacts = getContacts();
//    $companies = getCompanies();
//    return view('contact.index', [
//        "contacts"=>$contacts,
//        "companies"=>$companies
//    ]);
//})->name("contacts.index");
//
//Route::get('/contacts/create', function () {
//    return view('contact.create');
//})->name("contacts.create");
//
//Route::get('/contacts/{id} ', function ($id) {
//    $contact = Contact::findOrFail($id);
//    return view('contact.show', ["contact"=>$contact]);
//})->name("contacts.show");


//Route::get('/contacts', [ContactsController::class, 'index'])->name("contacts.index");
//
//Route::get('/contacts/create', [ContactsController::class, 'create'])->name("contacts.create");
//
//Route::get('/contacts/{id} ', [ContactsController::class, 'show'])->name("contacts.show");


//
//Route::group([
//    'as'=>"contacts.",
//    'prefix'=>"/contacts",
//], function () {
//    Route::get('/', [ContactsController::class, 'index'])->name("index");
//    //        C 3 > Q 2
//    Route::post('/', [ContactsController::class, 'store'])->name("store");
//    Route::get('/create', [ContactsController::class, 'create'])->name("create");
//    Route::get('/{id} ', [ContactsController::class, 'show'])->name("show");
//});

Route::resource('/companies', CompanyController::class);
Route::resource('/contacts', ContactsController::class);


Route::group([
    'as' => "trush.",
    'prefix' => "/trush",
], function () {
    Route::resource('/contacts', TrushContactsController::class)
        ->only(['index', 'update', 'destroy']);
    Route::resource('/companies', TrushCompanyController::class)
        ->only(['index', 'update', 'destroy']);
});


Route::resources([
    'tag' => TagsController::class,
    'task' => TaskController::class
]);

Route::resource('/activity', ActivityController::class)
    ->only(['create', 'store', 'edit', 'update', 'destroy']);
Route::resource('/activity', ActivityController::class)
    ->except(['index', 'show']);

Route::resource('contact.note', ContactNoteController::class)
    ->shallow();

//Route::get('/ContactAdmin', [ContactsAdminController::class, 'index'])
//    ->middleware('check-user');

//Route::get('/ContactAdmin', [ContactsAdminController::class, 'index'])
//    ->middleware(['check-user', 'check-user-actif']);

Route::get('/ContactAdmin', [ContactsAdminController::class, 'index'])
    ->middleware('check');

app/Models/Contact.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Contact extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $guarded = [];

    public function company()
    {
        return $this->belongsTo(Company::class);
    }
}

app/Http/Controllers/ContactsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreContactRequests;
use App\Http\Requests\UpdateContactRequests;
use App\Models\Company;
use App\Models\Contact;
use Illuminate\Http\Request;

class ContactsController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(Request $request)
    {
//        C6 Q3 a
//        $contacts = Contact::all();
//        C6 Q3 b
//        $contacts_first_3 = Contact::take(3)->get();
//        C6 Q3 c
//        $contacts_first_3_after_5 = Contact::skip(5)->take(3)->get();

//        C6 Q11
        $contacts = Contact::query();
        if ($request->filled('company_id')) {
            $contacts->where('company_id', $request->company_id);
        }
        $contacts = $contacts->get();


        $companies = Company::all();
        return view('contacts.index', [
            "contacts" => $contacts,
            "companies" => $companies
        ]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $companies = Company::all();
        return view('contacts.create', [
            "companies" => $companies
        ]);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreContactRequests $request)
    {
//        C6 Q3 d
//        $contact = new Contact();
//        $contact->first_name = $request->first_name;
//        $contact->last_name = $request->last_name;
//        $contact->phone = $request->phone;
//        $contact->email = $request->email;
//        $contact->address = $request->address;
//        $contact->company_id = $request->company_id;
//        $contact->save();

//        C6 Q3 e
        Contact::create($request->all());

//        C6 Q3 f
        Contact::firstOrCreate(
            ['email' => $request->email],
            $request->all()
        );

        return redirect()->route('contacts.index');
    }

    /**
     * Display the specified resource.
     */
    public function show(Contact $contact)
    {
        return view('contacts.show', ["contact" => $contact]);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Contact $contact)
    {
        $companies = Company::all();
        return view('contacts.edit', ["contact" => $contact, "companies" => $companies]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateContactRequests $request, Contact $contact)
    {

//        C6 Q3 g
//        $contact->first_name = $request->first_name;
//        $contact->last_name = $request->last_name;
//        $contact->phone = $request->phone;
//        $contact->email = $request->email;
//        $contact->address = $request->address;
//        $contact->company_id = $request->company_id;
//        $contact->save();

//        C6 Q3 h
        $contact->update($request->all());
        return redirect()->route('contacts.index');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Contact $contact)
    {
//        C6 Q3 i
        $contact->delete();
        return redirect()->route('contacts.index');
    }
}

resources/views/contacts/_company-selection.blade.php
<select id="company_id" name="company_id" class="custom-select">
    <option value="">Select a company</option>
    @foreach($companies as $companie)
        <option value="{{ $companie->id }}">{{ $companie->name }}</option>
    @endforeach
</select>

resources/views/contacts/_filter.blade.php
<div class="input-group">
  <input type="text" class="form-control" placeholder="Search" aria-label="Search" aria-describedby="basic-addon2">
  <div class="input-group-append">
    <button class="btn btn-outline-secondary" type="reset">reset</button>
    <button class="btn btn-outline-secondary" type="submit">submit</button>
  </div>
</div>

resources/views/contacts/create.blade.php
@extends('layouts.main')

@section("content")
    <div class="container">
        <div class="card rounded">
            <div class="card-header bg-secondary text-light">
                <h2 class="">Add New Contact</h2>
            </div>
            <div class="card-body p-3">
                <form method="post" action="{{ route("contacts.store") }}">
                    @csrf
                    <div class="form-group">
                        <label for="first_name">First Name</label>
                        <input
                            type="text"
                            id="first_name"
                            name="first_name"
                            value="{{ old('first_name') }}"
                            class="form-control"
                        >
                        @if ($errors->has('first_name'))
                            <span class="text-danger">{{ $errors->first('first_name') }}</span>
                        @endif
                    </div>
                    <div class="form-group">
                        <label for="last_name">Last Name</label>
                        <input
                            type="text"
                            id="last_name"
                            name="last_name"
                            value="{{ old('last_name') }}"
                            class="form-control"
                        >
                        @if ($errors->has('last_name'))
                            <span class="text-danger">{{ $errors->first('last_name') }}</span>
                        @endif
                    </div>
                    <div class="form-group">
                        <label for="email">Email</label>
                        <input
                            type="email"
                            id="email"
                            name="email"
                            value="{{ old('email') }}"
                            class="form-control"
                        >
                        @if ($errors->has('email'))
                            <span class="text-danger">{{ $errors->first('email') }}</span>
                        @endif
                    </div>
                    <div class="form-group">
                        <label for="phone">Phone</label>
                        <input
                            type="text"
                            id="phone"
                            name="phone"
                            value="{{ old('phone') }}"
                            class="form-control"
                        >
                        @if ($errors->has('phone'))
                            <span class="text-danger">{{ $errors->first('phone') }}</span>
                        @endif
                    </div>
                    <div class="form-group">
                        <label for="address">Address</label>
                        <textarea
                            id="address"
                            name="address"
                            class="form-control"
                        >{{ old('address') }}</textarea>
                        @if ($errors->has('address'))
                            <span class="text-danger">{{ $errors->first('address') }}</span>
                        @endif
                    </div>
                    <div class="form-group">
                        <label for="company">Company</label>
                        <select
                            id="company"
                            name="company_id"
                            class="form-control"
                        >
                            <option value="">Select a company</option>
                            @foreach($companies as $company)
                                <option value="{{ $company->id }}" {{ old('company_id') == $company->id ? 'selected' : '' }}>{{ $company->name }}</option>
                            @endforeach
                        </select>
                        @if ($errors->has('company_id'))
                            <span class="text-danger">{{ $errors->first('company_id') }}</span>
                        @endif
                    </div>
                    <div class="d-flex justify-content-between">
                        <button type="submit" class="btn btn-primary">Save</button>
                        <button type="reset" class="btn btn-secondary">Cancel</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

@endsection

resources/views/contacts/edit.blade.php
@extends('layouts.main')

@section("content")
    <div class="container">
        <div class="card rounded">
            <div class="card-header bg-secondary text-light">
                <h2 class="">Edit Contact</h2>
            </div>
            <div class="card-body p-3">
                <form method="post" action="{{ route("contacts.update", $contact->id) }}">
                    @csrf
                    @method('PUT')
                    <div class="form-group">
                        <label for="first_name">First Name</label>
                        <input
                            type="text"
                            id="first_name"
                            name="first_name"
                            value="{{ old('first_name', $contact->first_name) }}"
                            class="form-control"
                        >
                        @if ($errors->has('first_name'))
                            <span class="text-danger">{{ $errors->first('first_name') }}</span>
                        @endif
                    </div>
                    <div class="form-group">
                        <label for="last_name">Last Name</label>
                        <input
                            type="text"
                            id="last_name"
                            name="last_name"
                            value="{{ old('last_name', $contact->last_name) }}"
                            class="form-control"
                        >
                        @if ($errors->has('last_name'))
                            <span class="text-danger">{{ $errors->first('last_name') }}</span>
                        @endif
                    </div>
                    <div class="form-group">
                        <label for="email">Email</label>
                        <input
                            type="email"
                            id="email"
                            name="email"
                            value="{{ old('email', $contact->email) }}"
                            class="form-control"
                        >
                        @if ($errors->has('email'))
                            <span class="text-danger">{{ $errors->first('email') }}</span>
                        @endif
                    </div>
                    <div class="form-group">
                        <label for="phone">Phone</label>
                        <input
                            type="text"
                            id="phone"
                            name="phone"
                            value="{{ old('phone', $contact->phone) }}"
                            class="form-control"
                        >
                        @if ($errors->has('phone'))
                            <span class="text-danger">{{ $errors->first('phone') }}</span>
                        @endif
                    </div>
                    <div class="form-group">
                        <label for="address">Address</label>
                        <textarea
                            id="address"
                            name="address"
                            class="form-control"
                        >{{ old('address', $contact->address) }}</textarea>
                        @if ($errors->has('address'))
                            <span class="text-danger">{{ $errors->first('address') }}</span>
                        @endif
                    </div>
                    <div class="form-group">
                        <label for="company">Company</label>
                        <select
                            id="company"
                            name="company_id"
                            class="form-control"
                        >
                            <option value="">Select a company</option>
                            @foreach($companies as $company)
                                <option value="{{ $company->id }}" {{ old('company_id', $contact->company_id) == $company->id ? 'selected' : '' }}>{{ $company->name }}</option>
                            @endforeach
                        </select>
                        @if ($errors->has('company_id'))
                            <span class="text-danger">{{ $errors->first('company_id') }}</span>
                        @endif
                    </div>
                    <div class="d-flex justify-content-between">
                        <button type="submit" class="btn btn-primary">Save</button>
                        <button type="reset" class="btn btn-secondary">Cancel</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

@endsection

resources/views/contacts/index.blade.php
@extends('layouts.main')

@section("content")
    <div>
        <div class="d-flex justify-content-between bg-secondary p-3 rounded">
            <h2 class="text-light">All Contacts</h2>
            <a href="{{ route('contacts.create') }}" class="btn btn-light">Add New</a>
        </div>
        <div class="my-3">
            <form method="get" action="{{ route('contacts.index') }}">
                @csrf
                <div class="d-flex justify-content-end">
                    @includeUnless(empty($companies), 'contacts._company-selection')
                    @include('contacts._filter')
                </div>
            </form>
        </div>
        @if($contacts->count() > 0)
            <table class="table table-striped">
                <tr>
                    <th>#</th>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Phone</th>
                    <th>Email</th>
                    <th>Company</th>
                    <th>Actions</th>
                </tr>
                @foreach($contacts as $contact)
                    <tr>
                        <td>{{$contact->id}}</td>
                        <td>{{$contact->first_name}}</td>
                        <td>{{$contact->last_name}}</td>
                        <td>{{$contact->phone}}</td>
                        <td>{{$contact->email}}</td>
                        <td>{{$contact->company_id}}</td>
                        <td>
                            <div class="btn-group">
                                <a href="{{ route('contacts.show', ['contact'=> $contact->id]) }}"
                                   class="btn btn-primary">Show</a>
                                <a href="{{ route('contacts.edit', ['contact'=> $contact->id]) }}"
                                   class="btn btn-warning">Edit</a>
                                <form action="{{ route('contacts.destroy', $contact->id) }}" method="post">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn btn-danger">Delete</button>
                                </form>
                            </div>
                        </td>
                    </tr>
                @endforeach
            </table>
        @else
            <div class="alert alert-info">No contacts found.</div>
        @endif
    </div>
@endsection

resources/views/contacts/show.blade.php
@extends('layouts.main')

@section("content")
    <div class="container">
        <div class="card rounded">
            <div class="card-header bg-secondary text-light">
                <h2>Contact:</h2>
            </div>
            <div class="card-body p-3">
                <table class="table table-borderless">
                    <tr>
                        <th>First Name</th>
                        <td>{{ $contact->first_name }}</td>
                    </tr>
                    <tr>
                        <th>Last Name</th>
                        <td>{{ $contact->last_name }}</td>
                    </tr>
                    <tr>
                        <th>Phone</th>
                        <td>{{ $contact->phone }}</td>
                    </tr>
                    <tr>
                        <th>Email</th>
                        <td>{{ $contact->email }}</td>
                    </tr>
                    <tr>
                        <th>Company</th>
                        <td>{{ $contact->company_id }}</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
@endsection

resources/views/contacts/trush_contacts.blade.php
@extends('layouts.main')

@section("content")
    <div>
        <div class="d-flex justify-content-between bg-secondary p-3 rounded">
            <h2 class="text-light">Deleted Contacts</h2>
        </div>
        <div class="my-3">
            <form method="get" action="{{ route('trush.contacts.index') }}">
                @csrf
                <div class="d-flex justify-content-end">
                    @includeUnless(empty($companies), 'contacts._company-selection')
                    @include('contacts._filter')
                </div>
            </form>
        </div>
        @if($contacts->count() > 0)
            <table class="table table-striped">
                <tr>
                    <th>#</th>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Phone</th>
                    <th>Email</th>
                    <th>Company</th>
                    <th>Actions</th>
                </tr>
                @foreach($contacts as $contact)
                    <tr>
                        <td>{{$contact->id}}</td>
                        <td>{{$contact->first_name}}</td>
                        <td>{{$contact->last_name}}</td>
                        <td>{{$contact->phone}}</td>
                        <td>{{$contact->email}}</td>
                        <td>{{$contact->company_id}}</td>
                        <td>
                            <div class="btn-group">
                                <form action="{{ route('trush.contacts.update', $contact->id) }}" method="post">
                                    @csrf
                                    @method('PUT')
                                    <button type="submit" class="btn btn-primary">Restore</button>
                                </form>
                                <form action="{{ route('trush.contacts.destroy', $contact->id) }}" method="post">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn btn-danger">Delete definitely</button>
                                </form>
                            </div>
                        </td>
                    </tr>
                @endforeach
            </table>
        @else
            <div class="alert alert-info">No contacts found.</div>
        @endif
    </div>
@endsection