routes/web.php
<?php

use App\Http\Controllers\ActivityController;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\ContactNoteController;
use App\Http\Controllers\ContactsAdminController;
use App\Http\Controllers\ContactsController;
use App\Http\Controllers\TagsController;
use App\Http\Controllers\TaskController;
use App\Http\Controllers\TrushCompanyController;
use App\Http\Controllers\TrushContactsController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

//Route::get('/contacts', function () {
//    $contacts = getContacts();
//    $companies = getCompanies();
//    return view('contact.index', [
//        "contacts"=>$contacts,
//        "companies"=>$companies
//    ]);
//})->name("contacts.index");
//
//Route::get('/contacts/create', function () {
//    return view('contact.create');
//})->name("contacts.create");
//
//Route::get('/contacts/{id} ', function ($id) {
//    $contact = Contact::findOrFail($id);
//    return view('contact.show', ["contact"=>$contact]);
//})->name("contacts.show");


//Route::get('/contacts', [ContactsController::class, 'index'])->name("contacts.index");
//
//Route::get('/contacts/create', [ContactsController::class, 'create'])->name("contacts.create");
//
//Route::get('/contacts/{id} ', [ContactsController::class, 'show'])->name("contacts.show");


//
//Route::group([
//    'as'=>"contacts.",
//    'prefix'=>"/contacts",
//], function () {
//    Route::get('/', [ContactsController::class, 'index'])->name("index");
//    //        C 3 > Q 2
//    Route::post('/', [ContactsController::class, 'store'])->name("store");
//    Route::get('/create', [ContactsController::class, 'create'])->name("create");
//    Route::get('/{id} ', [ContactsController::class, 'show'])->name("show");
//});

Route::resource('/companies', CompanyController::class);
Route::resource('/contacts', ContactsController::class);


Route::group([
    'as' => "trush.",
    'prefix' => "/trush",
], function () {
    Route::resource('/contacts', TrushContactsController::class)
        ->only(['index', 'update', 'destroy']);
    Route::resource('/companies', TrushCompanyController::class)
        ->only(['index', 'update', 'destroy']);
});


Route::resources([
    'tag' => TagsController::class,
    'task' => TaskController::class
]);

Route::resource('/activity', ActivityController::class)
    ->only(['create', 'store', 'edit', 'update', 'destroy']);
Route::resource('/activity', ActivityController::class)
    ->except(['index', 'show']);

Route::resource('contact.note', ContactNoteController::class)
    ->shallow();

//Route::get('/ContactAdmin', [ContactsAdminController::class, 'index'])
//    ->middleware('check-user');

//Route::get('/ContactAdmin', [ContactsAdminController::class, 'index'])
//    ->middleware(['check-user', 'check-user-actif']);

Route::get('/ContactAdmin', [ContactsAdminController::class, 'index'])
    ->middleware('check');

app/Models/Company.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Company extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $table = 'companies';

    protected $guarded = [];

    public function contacts()
    {
        return $this->hasMany(Contact::class);
    }
}

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreCompanyRequests;
use App\Http\Requests\UpdateCompanyRequests;
use App\Models\Company;

class CompanyController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $companies = Company::all();
        return view('companies.index',[
            "companies" => $companies
        ]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('companies.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreCompanyRequests $request)
    {
        Company::create($request->all());
        return redirect()->route('companies.index');
    }

    /**
     * Display the specified resource.
     */
    public function show(Company $company)
    {
        return view('companies.show', ["company"=>$company]);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Company $company)
    {
        return view('companies.edit', ["company"=>$company]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateCompanyRequests $request, Company $company)
    {
        $company->update($request->all());
        return redirect()->route('companies.index');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Company $company)
    {
        $company->delete();
        return redirect()->route('companies.index');
    }
}

resources/views/companies/create.blade.php
@extends('layouts.main')

@section("content")
    <div class="container">
        <div class="card rounded">
            <div class="card-header bg-secondary text-light">
                <h2 class="">Add New Company</h2>
            </div>
            <div class="card-body p-3">
                <form method="post" action="{{ route("companies.store") }}">
                    @csrf
                    <div class="form-group">
                        <label for="name">Name</label>
                        <input
                            type="text"
                            id="name"
                            name="name"
                            value="{{ old('name') }}"
                            class="form-control"
                        >
                        @if ($errors->has('name'))
                            <span class="text-danger">{{ $errors->first('name') }}</span>
                        @endif
                    </div>
                    <div class="form-group">
                        <label for="email">Email</label>
                        <input
                            type="email"
                            id="email"
                            name="email"
                            value="{{ old('email') }}"
                            class="form-control"
                        >
                        @if ($errors->has('email'))
                            <span class="text-danger">{{ $errors->first('email') }}</span>
                        @endif
                    </div>
                    <div class="form-group">
                        <label for="website">Website</label>
                        <input
                            type="text"
                            id="website"
                            name="website"
                            value="{{ old('website') }}"
                            class="form-control"
                        >
                        @if ($errors->has('website'))
                            <span class="text-danger">{{ $errors->first('website') }}</span>
                        @endif
                    </div>
                    <div class="form-group">
                        <label for="address">Address</label>
                        <textarea
                            id="address"
                            name="address"
                            class="form-control"
                        >{{ old('address') }}</textarea>
                        @if ($errors->has('address'))
                            <span class="text-danger">{{ $errors->first('address') }}</span>
                        @endif
                    </div>
                    <div>
                        <button type="submit" class="btn btn-primary">Save</button>
                        <button type="reset" class="btn btn-secondary">Cancel</button>
                    </div>
                </form>
            </div>
        </div>
@endsection

resources/views/companies/edit.blade.php
@extends('layouts.main')

@section("content")
    <div class="container">
        <div class="card rounded">
            <div class="card-header bg-secondary text-light">
                <h2 class="">Edit Company</h2>
            </div>
            <div class="card-body p-3">
                <form method="post" action="{{ route("companies.update", $company->id) }}">
                    @csrf
                    @method('put')
                    <div class="form-group">
                        <label for="name">Name</label>
                        <input
                            type="text"
                            id="name"
                            name="name"
                            value="{{ old('name', $company->name) }}"
                            class="form-control"
                        >
                        @if ($errors->has('name'))
                            <span class="text-danger">{{ $errors->first('name') }}</span>
                        @endif
                    </div>
                    <div class="form-group">
                        <label for="email">Email</label>
                        <input
                            type="email"
                            id="email"
                            name="email"
                            value="{{ old('email', $company->email) }}"
                            class="form-control"
                        >
                        @if ($errors->has('email'))
                            <span class="text-danger">{{ $errors->first('email') }}</span>
                        @endif
                    </div>
                    <div class="form-group">
                        <label for="website">Website</label>
                        <input
                            type="text"
                            id="website"
                            name="website"
                            value="{{ old('website', $company->website) }}"
                            class="form-control"
                        >
                        @if ($errors->has('website'))
                            <span class="text-danger">{{ $errors->first('website') }}</span>
                        @endif
                    </div>
                    <div class="form-group">
                        <label for="address">Address</label>
                        <textarea
                            id="address"
                            name="address"
                            class="form-control"
                        >{{ old('address', $company->address) }}</textarea>
                        @if ($errors->has('address'))
                            <span class="text-danger">{{ $errors->first('address') }}</span>
                        @endif
                    </div>
                    <div>
                        <button type="submit" class="btn btn-primary">Update</button>
                        <button type="reset" class="btn btn-secondary">Cancel</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/companies/index.blade.php
@extends('layouts.main')

@section("content")
    <div>
        <div class="d-flex justify-content-between bg-secondary p-3 rounded">
            <h2 class="text-light">All Companies</h2>
            <a href="{{ route('companies.create') }}" class="btn btn-light">Add New</a>
        </div>
        @if($companies->count() > 0)
            <table class="table table-striped table-bordered">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>Address</th>
                    <th>Email</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                @foreach($companies as $company)
                    <tr>
                        <td>{{$company->id}}</td>
                        <td>{{$company->name}}</td>
                        <td>{{$company->address}}</td>
                        <td>{{$company->email}}</td>
                        <td>
                            <div class="btn-group">
                                <a href="{{ route('companies.show', $company->id) }}" class="btn btn-primary">Show</a>
                                <a href="{{ route('companies.edit', $company->id) }}" class="btn btn-warning">Edit</a>
                                <form action="{{ route('companies.destroy', $company->id) }}" method="post">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn btn-danger">Delete</button>
                                </form>
                            </div>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        @else
            <div class="alert alert-info">No companies found.</div>
        @endif
    </div>
@endsection

resources/views/companies/show.blade.php
@extends('layouts.main')

@section("content")
    <div class="container">
        <div class="card rounded">
            <div class="card-header bg-secondary text-light">
                <h2>Company:</h2>
            </div>
            <div class="card-body p-3">
                <table class="table table-borderless">
                    <tr>
                        <th style="width: 150px;">Name</th>
                        <td>{{ $company->name }}</td>
                    </tr>
                    <tr>
                        <th>Email</th>
                        <td>{{ $company->email }}</td>
                    </tr>
                    <tr>
                        <th>Website</th>
                        <td>{{ $company->website }}</td>
                    </tr>
                    <tr>
                        <th>Address</th>
                        <td>{{ $company->address }}</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
@endsection

resources/views/companies/trush_companies.blade.php
@extends('layouts.main')

@section("content")
    <div>
        <div class="d-flex justify-content-between bg-secondary p-3 rounded">
            <h2 class="text-light">Deleted Companies</h2>
        </div>
        @if($companies->count() > 0)
            <table class="table table-striped table-bordered">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>Address</th>
                    <th>Email</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                @foreach($companies as $company)
                    <tr>
                        <td>{{$company->id}}</td>
                        <td>{{$company->name}}</td>
                        <td>{{$company->address}}</td>
                        <td>{{$company->email}}</td>
                        <td>
                            <div class="btn-group">
                                <form action="{{ route('trush.companies.update', $company->id) }}" method="post">
                                    @csrf
                                    @method('PUT')
                                    <button type="submit" class="btn btn-primary">Restore</button>
                                </form>
                                <form action="{{ route('trush.companies.destroy', $company->id) }}" method="post">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn btn-danger">Delete definitely</button>
                                </form>
                            </div>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        @else
            <div class="alert alert-info">No companies found.</div>
        @endif
    </div>
@endsection