routes/web.php
<?php

use App\Http\Controllers\ActivityController;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\ContactNoteController;
use App\Http\Controllers\ContactsAdminController;
use App\Http\Controllers\ContactsController;
use App\Http\Controllers\TagsController;
use App\Http\Controllers\TaskController;
use App\Http\Controllers\TrushCompanyController;
use App\Http\Controllers\TrushContactsController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

//Route::get('/contacts', function () {
//    $contacts = getContacts();
//    $companies = getCompanies();
//    return view('contact.index', [
//        "contacts"=>$contacts,
//        "companies"=>$companies
//    ]);
//})->name("contacts.index");
//
//Route::get('/contacts/create', function () {
//    return view('contact.create');
//})->name("contacts.create");
//
//Route::get('/contacts/{id} ', function ($id) {
//    $contact = Contact::findOrFail($id);
//    return view('contact.show', ["contact"=>$contact]);
//})->name("contacts.show");


//Route::get('/contacts', [ContactsController::class, 'index'])->name("contacts.index");
//
//Route::get('/contacts/create', [ContactsController::class, 'create'])->name("contacts.create");
//
//Route::get('/contacts/{id} ', [ContactsController::class, 'show'])->name("contacts.show");


//
//Route::group([
//    'as'=>"contacts.",
//    'prefix'=>"/contacts",
//], function () {
//    Route::get('/', [ContactsController::class, 'index'])->name("index");
//    //        C 3 > Q 2
//    Route::post('/', [ContactsController::class, 'store'])->name("store");
//    Route::get('/create', [ContactsController::class, 'create'])->name("create");
//    Route::get('/{id} ', [ContactsController::class, 'show'])->name("show");
//});

Route::resource('/companies', CompanyController::class);
Route::resource('/contacts', ContactsController::class);


Route::group([
    'as' => "trush.",
    'prefix' => "/trush",
], function () {
    Route::resource('/contacts', TrushContactsController::class)
        ->only(['index', 'update', 'destroy']);
    Route::resource('/companies', TrushCompanyController::class)
        ->only(['index', 'update', 'destroy']);
});


Route::resources([
    'tag' => TagsController::class,
    'task' => TaskController::class
]);

Route::resource('/activity', ActivityController::class)
    ->only(['create', 'store', 'edit', 'update', 'destroy']);
Route::resource('/activity', ActivityController::class)
    ->except(['index', 'show']);

Route::resource('contact.note', ContactNoteController::class)
    ->shallow();

//Route::get('/ContactAdmin', [ContactsAdminController::class, 'index'])
//    ->middleware('check-user');

//Route::get('/ContactAdmin', [ContactsAdminController::class, 'index'])
//    ->middleware(['check-user', 'check-user-actif']);

Route::get('/ContactAdmin', [ContactsAdminController::class, 'index'])
    ->middleware('check');

resources/views/layouts/_navbar.blade.php
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand text-danger" href="{{ url('/') }}">CONTACT-APP</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{{ route('companies.index') }}">Companies <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ route('contacts.index') }}">Contacts</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Trush
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{{ route('trush.companies.index') }}">Companies</a>
          <a class="dropdown-item" href="{{ route('trush.contacts.index') }}">Contacts</a>
        </div>
      </li>
    </ul>
  </div>
</nav>

resources/views/layouts/main.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Laravel Layout</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>

<header>
    @include("layouts._navbar")
</header>

<div class="container mt-4">
    @yield('content')
</div>

<footer class="mt-4 bg-light text-center">
    @yield('footer')
</footer>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>